
--DDL (데이터 정의어)
-- 테이블 생성하기
CREATE TABLE BOARD (
-- 글번호, 제목, 내용, 작성자, 시간
-- 제약조건 NOT NULL / 필수로 입력되야 한다.
    BNO NUMBER(10),
    TITLE VARCHAR2(200)NOT NULL,
    CONTENT VARCHAR2(2000),
    WRITER VARCHAR2(50)NOT NULL,
    REG_DATE DATE NOT NULL
);

-- NUMBER(5,2) = 999.99까지 / 총 5자리에 뒷자리 2개(실수)

-- PRIMARY KEY(기본키) 설정
ALTER TABLE BOARD
ADD CONSTRAINT pk_board_bno
PRIMARY KEY(BNO);

-- 조회
SELECT*FROM BOARD;
SELECT*FROM REPLY;

-- 댓글
CREATE TABLE REPLY (
 RNO NUMBER(10),
 R_CONTENT VARCHAR2(1000),
 R_WRITER VARCHAR2(50)NOT NULL,
 BNO NUMBER(10)
);

--PK 설정
ALTER TABLE REPLY
ADD CONSTRAINT pk_reply_rno
PRIMARY KEY (RNO);

-- FK 설정
ALTER TABLE REPLY
ADD CONSTRAINT fk_reply_bno
FOREIGN KEY(BNO)
REFERENCES BOARD(BNO);

-- 컬럼 변경

-- BOARD에 VIEW_COUNT라는 정수 컬럼(셀)을 추가한다.
ALTER TABLE BOARD ADD(VIEW_COUNT NUMBER(10));

-- BOARD에서 날짜 컬럼(셀) 삭제
ALTER TABLE BOARD DROP COLUMN REG_DATE;

-- TABLE 자체를 삭제
--DROP TABLE REPLY;
--DROP TABLE BOARD;
